---
- hosts: localhost
  connection: local 
  become: yes               
  become_method: sudo       
  remote_user: ubuntu       
  
  vars:
    tomcat_ver: 9.0.62                      
    ui_manager_user: janedo                    
    ui_manager_pass: passwd                    
    ui_admin_username: janedo                  
    ui_admin_pass: passwd   

  roles:
    - tomcat9
  
  tasks:
    - name: Move citizen.war to Tomcat
      command: mv ~/citizen.war /usr/share/tomcat/webapps/citizen.war;

    - name: Restart Tomcat
      command: systemctl restart tomcat.service
