---
- hosts: all                 

  become: yes               
  become_method: sudo       
  remote_user: ubuntu       
  
  tasks:

  - name: Execute Tomcat startup.sh
    script: sh ../UPD_IP_in_tomcat_citizen.sh
