---
- hosts: all                 

  become: yes               
  become_method: sudo       
  remote_user: ubuntu       
  
  tasks:
  - name: Update IPs in /tomcat/webapps/citizen
    script: ./UPD_IP_in_tomcat_citizen.sh
