---
- hosts: all                 

  become: yes               
  become_method: sudo       
  remote_user: ubuntu       
  
  vars:
    tomcat_ver: 9.0.62                      
    ui_manager_user: janedo                    
    ui_manager_pass: passwd                    
    ui_admin_username: janedo                  
    ui_admin_pass: passwd   

  roles:
    - tomcat9
  
  tasks:
  - name: Delete citizen from Tomcat
    command: rm -rf /usr/share/tomcat/webapps/citizen.war; rm -rf /usr/share/tomcat/webapps/citizen

  - name: Copy citizen.war from local to remote
    copy:
      src: ../target/citizen.war
      dest: /usr/share/tomcat/webapps/

  - name: Execute Tomcat startup.sh
    command: sh /usr/share/tomcat/bin/startup.sh
