---
- hosts: all                 

  become: yes               
  become_method: sudo       
  remote_user: ubuntu       
  
  vars:
    tomcat_ver: 9.0.60         

  roles:
    - tomcat9
  
  tasks:
  - include_vars: vars.yml
  
  - name: Install Git
    become: yes
    apt:
      name: git
      state: present

  - name: Copy files from local to remote
    copy:
      src: ../target/citizen.war
      dest: /usr/share/tomcat/webapps/
      mode: 0777

  - name: Execute Tomcat startup.sh
    command: sh /usr/share/tomcat/bin/startup.sh
