---
- hosts: all                 

  become: yes               
  become_method: sudo       
  remote_user: ubuntu       
  
  vars:
    tomcat_ver: 9.0.60                         
    ui_manager_user: janedo                    
    ui_manager_pass: passwd                    
    ui_admin_username: janedo                  
    ui_admin_pass: passwd         

  # roles:
  #   - tomcat9
  
  tasks:
  # - name: Install Maven, Git
  #   become: yes
  #   apt:
  #     name: "{{ packages }}"
  #     state: present
  #   vars:
  #     packages:
  #         - maven
  #         - git

  - name: Copy files from local to remote
    copy:
      src: "{{ item }}"
      dest: ~/
      mode: 0777
    with_items:
      - "~/DevOpsChernivtsi/GeoCitizen/AWS.Terraform+Ansible/emailCredentials"
      - "~/DevOpsChernivtsi/GeoCitizen/AWS.Terraform+Ansible/Terraform/details/credentials"

  - name: Execute cleanDeploy.sh
    script: ~/DevOpsChernivtsi/GeoCitizen/AWS.Terraform+Ansible/cleanD.sh
      