---
- hosts: all                 

  become: yes               
  become_method: sudo       
  remote_user: ubuntu       
  
  vars:
    tomcat_ver: 9.0.60         

  roles:
    - tomcat9
  
  tasks:
  - include_vars: vars.yml
  - name: Install Maven, Git
    become: yes
    apt:
      name: "{{ packages }}"
      state: present
    vars:
      packages:
          - maven
          - git

#   - name: Copy files from local to remote
#     copy:
#       src: "{{ item }}"
#       dest: ~/
#       mode: 0777
#     with_items:
#       - "../emailCredentials"
#       - "../Terraform/details/credentials"

#   - name: Execute cleanDeploy.sh
#     script: ../deploy.sh
      
